name: Cypress Tests

on:
  push:
    branches:
      - master

# Permissões para o job poder escrever nas GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependências
        run: npm install

      - name: Rodar testes Cypress
        uses: cypress-io/github-action@v6

      - name: Preparar artefato do relatório para deploy
        if: always()
        uses: actions/upload-pages-artifact@v3
        with:
          path: cypress/reports

